// services/protocolConfig.js

// ==============================
// HARDCODED FIELDS
// ==============================

export const HARDCODED_TOUCHPOINT_FIELDS = {
  n4f_touchpoint_type: "Event booth meeting",
  n4f_activity_status: "Booth discussion"
};

// ==============================
// VALID ENUMS
// ==============================

export const VALID_EVENTS = [
  "ALSC Digital",
  "ALSC Europe",
  "ALSC Global",
  "ASUG Best Practices",
  "ASUG Tech Connect",
  "BSMA Europe",
  "CSCMP EDGE",
  "DELIVER Europe",
  "Digital Supply Chain Summit",
  "DSAG Jahreskongress",
  "European Supply Chain Management Strategies Summit",
  "European Supply Chain Summit",
  "Forum Automobillogistik",
  "Gartner London",
  "Gartner Orlando",
  "Gartner Supply Chain Planning Summit",
  "Gartner Supply Chain Symposium/Xpo",
  "GDS",
  "ICT & Logistiek Utrecht",
  "Kinexions",
  "Kinexions EMEA",
  "LOG.NET",
  "LogiMAT",
  "LogiMed",
  "LogiPharma",
  "LogiPharma Connect",
  "LogiPharma Digital SC Connect",
  "Makers & Movers",
  "Manifest",
  "MODEX",
  "North American SC Executive Summit",
  "Pit Stop Supply Chain",
  "ProMat",
  "SAP Connect Days for Supply Chain",
  "SAP Discovery Day",
  "SAP Innovation Day",
  "SAP Sapphire & ASUG Annual Conference",
  "SAPinsider Las Vegas",
  "SAPinsider Technology & Innovation Summit",
  "SCMWorX",
  "SITL",
  "SMC3 Jump Start Atlanta",
  "Supply Chain Forum",
  "Tender Management Konferenz",
  "Test Event",
  "TFEST",
  "Translog",
  "transport logistic",
  "Visibility now",
  "Visibility now Online Event",
  "X-PLAN",
  "Zero100 Live"
];

export const VALID_QUALITY = [
  "Sales potential",
  "Sales potential unclear",
  "Contact maintenance",
  "Vendor",
  "Competitor",
  "Other",
  "Partner"
];

export const VALID_TOPICS = [
  "SAP Digital Supply Chain",
  "4flow software solutions",
  "Warehousing and intralogistics",
  "General interest in 4flow",
  "tbd"
];

export const VALID_BUSINESS_LINES = [
  "4fc",
  "4fm",
  "4fs",
  "4fc-SAP",
  "4fc-Kinaxis",
  "4flow"
];

export const VALID_USERS = [
"Akhilesh Mohan",
"Alain Joyeux",
"Alexander Deger",
"Alexandra Lorenzen",
"Anastasia Vosswinkel",
"Andreas Weber",
"Antoine Clogne",
"Aretha Omena",
"Beatriz Lourenço",
"Benjamin Curro",
"Bernhard Höcherl",
"Bertrand Leroy",
"Bethany Claps",
"Bill Fan",
"Christian Lieberoth-Leden",
"Christian Schomann",
"Christian Siemering",
"Christoph Bewernick",
"Christoph Weber",
"Damian Unterlöhner",
"Daniela Santos",
"Darya Basarhina",
"David Salerno",
"Denis Reinhold",
"Diana Niggemann",
"Eliana D`Addezio",
"Elisabeth Moritz-Keidel",
"Fabian Loeper",
"Felix Kaemmerer",
"Felix Prestel",
"Ferdinand Grotz",
"Fernanda Rodrigues",
"Fernão Croce",
"Finn von Hammerstein",
"Florian Salamon",
"Grant Newsome",
"Greg Toornman",
"Helen Bower",
"Henrik Baumann",
"Henrique Silva",
"Igor Bartel",
"Ilya Labeika",
"Isabell Krause",
"Jan Fastenrath",
"Jan-Hendrik Kölling",
"Jan-Moritz Metelmann",
"Jan-Niklas Grafe",
"Jana Adam",
"Jens Buschfeld",
"Joachim Wittmack",
"John Choi",
"Jonas Goldenstein",
"Jörg Biermann",
"Joshua Brooks",
"Julian Schulcz",
"Julian Schwandt",
"Julius Maulbetsch",
"Kai Althoff",
"Kai Müller",
"Kai Peters",
"Katharina von Helldorff-Mager",
"Kevin Ingenwerth",
"Larissa Vilela",
"Leiv Klarmann",
"Lennart Brueggemann v. Ackern",
"Lukas Bouska",
"Lukas Sirch",
"Luis Gustavo Soares",
"Malte Vogt",
"Marc Schleyer",
"Marcela Ueda",
"Markus Eichner",
"Markus Koch",
"Markus Ungruhe",
"Martin Benning",
"Martin Wilson",
"Matthias Pfennig",
"Max Guhlke",
"Michael Capo",
"Michael Kagel",
"Michael Lundquist",
"Mihai Ploia",
"Naomi Apt",
"Natalia Andreyeva",
"Nicholas Meredith",
"Nicolas Madinier",
"Niklas Bergner",
"Nicola Lejeune",
"Patrick Vollet",
"Peter Gyurcsek",
"Pierre-Edward Taylor",
"Raina Pintamo",
"Ralph Eberspächer",
"Ralph-Michael Schmidt",
"Rani Kshepakaran",
"Robert Roggenfeld",
"Roger Sechler",
"Roody Jasmin",
"Sabrina Starke",
"Santiago Gunther",
"Sara Snider",
"Sarah Snider",
"Simon Franke",
"Sören Hagen",
"Sridhar Palepu",
"Srikanth Budati",
"Stefan Heidrich",
"Steffen v. Karstedt",
"Sylvain Dove",
"Tamas Kiss",
"TJ Keys",
"Tim Gerlach",
"Tobias Prien",
"Tobias Ziaja",
"Wilm Neubauer"
];
